# Generated by Django 5.0.6 on 2024-06-19 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_customer_file_upload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentprocess',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.employercompany'),
        ),
    ]
