# Generated by Django 5.0.6 on 2024-06-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_expenses_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
