# Generated by Django 5.0.6 on 2024-06-20 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_consultation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultation',
            old_name='date',
            new_name='consultation_date',
        ),
    ]
