# Generated by Django 5.0.6 on 2024-06-21 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_customer_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employercompany',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
