# Generated by Django 5.0.6 on 2024-06-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_fees_percentage_connectionfees_fees_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysettings',
            name='address',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='email',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='name',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='phone_number',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='customer',
            name='firstname',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='customer',
            name='othernames',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phonenumber_1',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phonenumber_2',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='employercompany',
            name='address',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='employercompany',
            name='email',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='employercompany',
            name='name',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='employercompany',
            name='phone_number',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='expense',
            name='name',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='feespayment',
            name='fee_type',
            field=models.CharField(choices=[('registration', 'Registration Fee'), ('consultation', 'Consultation Fee'), ('connection', 'Connection Fee')], max_length=254),
        ),
        migrations.AlterField(
            model_name='feespayment',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('partially_paid', 'Partially Paid')], default='unpaid', max_length=254),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_field',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_title',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='job_position',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='recruitmentprocess',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('pending', 'Pending'), ('interviewed', 'Interviewed'), ('not_hired', 'Not Hired'), ('hired', 'Hired'), ('rejected_offer', 'Rejected the Offer')], default='applied', max_length=254),
        ),
    ]
