# Generated by Django 5.0.6 on 2024-07-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_companysettings_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='date',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='date',
            new_name='date_added',
        ),
        migrations.AddField(
            model_name='job',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='jobposition',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='feespayment',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
