# Generated by Django 5.0.6 on 2024-07-06 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_date_customer_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
