# Generated by Django 5.0.6 on 2024-07-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_expense_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employercompany',
            name='phone_number2',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
