# Generated by Django 5.0.6 on 2024-07-31 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_companysettings_phonenumber_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connectionfees',
            name='fees_amount',
        ),
        migrations.AddField(
            model_name='connectionfees',
            name='percentage',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='feespayment',
            name='fee_type',
            field=models.CharField(choices=[('consultation_registration', 'Consultation / Registration Fee'), ('connection', 'Connection Fee')], max_length=254),
        ),
    ]
