# Generated by Django 5.0.6 on 2024-07-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_roles_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('staff', 'Staff'), ('accountant', 'Accountant'), ('admin', 'Admin')], default='staff', max_length=254),
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
