# Generated by Django 5.0.6 on 2024-07-06 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_customuser_role_delete_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pass_port_photo',
            field=models.ImageField(null=True, upload_to='user_images/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('staff', 'User Staff'), ('accountant', 'User Accountant'), ('admin', 'User Admin')], default='staff', max_length=254),
        ),
    ]
